### PR TITLE
journal-week-2 — Epicurean306.github.io

### PR DESCRIPTION
**Pull request by Epicurean306**
WIP branch in Epicurean306.github.io for journal-week-2

### CODE REVIEW

**Comment by kmattiko** [comment]
Nice job, I like the way you phrase things. You may want to consider breaking up that first sentence into smaller ones in your final draft. :+1:

**Comment by pcreglow** [comment]
Good start to reviewing the material that was covered in class. You will have another strong reference point when this journal entry is finished. :+1:

**Comment by al-the-x** [comment]
Do yourself a favor: don't use `&` in file names; `+` is okay, though.

**Comment by al-the-x** [comment]
Saw that banana there...

**Comment by JessyRiordan** [comment]
Great job Ben! :+1:

**Comment by gatorpazz** [comment]
Your journal entry will be treasured in the halls of the interwebs for years to come, 7/10 :+1:

**Pull request merged**
