### PR TITLE
journal-week-5

### PR DESCRIPTION
**Pull request by Epicurean306**

### CODE REVIEW

**Comment by MStaehling** [comment]
very thoughtful and enlightning :+1:

**Comment by pope410211** [comment]
:+1:  Hey Ben, good journals, I wish I would have added the `BG`, `FG`, `ctrl +c` commands.

**Comment by pcreglow** [comment]
Good tutorial. I wish I had read this prior to my browser-sync meltdown last evening.

**Comment by sjoyal** [comment]
Good journals sir, I completely forgot about pattern lab! I would throw in `jobs` and `fg %<job number>` commands for browser-sync as well. :+1:

**Comment by gatorpazz** [comment]
REFLECTIVE CORRECT TO "IT WOULD HAVE BEEN"!!!!! YUMMY TOOL TO USE!!!!!!!! THAT TUTORIAL SO GOOD!!!!!!!!!!!!! 7/10 C :+1: :+1: :+1:

**Pull request merged**
